# Generated by Django 2.2 on 2020-01-06 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc', models.FloatField(verbose_name='Total CTC')),
                ('appraisal_date', models.DateField(verbose_name='Appraisal Date')),
                ('is_current', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryBreakup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_frequency', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('S', 'Semi Annually'), ('A', 'Annually')], default='M', max_length=30)),
                ('amount', models.FloatField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Package_Component', to='salary.SalaryComponent')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CTC_Breakup', to='salary.SalaryPackage')),
            ],
        ),
    ]
